# Generated by Django 3.1.3 on 2020-12-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='SignUpUser',
        ),
    ]
